# Generated by Django 5.0.6 on 2024-05-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('mensaje', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
